spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5440/crypto_tracker}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# Tự động cập nhật / tạo bảng DB từ Entity của Spring Boot
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:true}

coingecko.api.key=${COINGECKO_API_KEY:xx-cg-demo-api-key}