spring.application.name=CryptoTracking

# Connect to Postgres inside Docker using port 5440
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5440/crypto_tracker}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration for Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}

# Server configuration
server.port=8088

# Connection configuration
coingecko.api.connect.timeout=3000
coingecko.api.read.timeout=5000
coingecko.api.key=${COINGECKO_API_KEY}

# Spring doc OpenAPI url
# Backend parse JSON
springdoc.api-docs.path=/api/v1/docs
# Frontend fetch data
springdoc.swagger-ui.url=/api/v1/docs

# Enable Liveness and Readiness Probes for Kubernetes
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health