apiVersion: v1
kind: Secret
metadata:
  name: crypto-tracker-secret
  labels:
    app: crypto-tracker
type: Opaque
data:
  DB_USERNAME: YWRtaW4=                  # "admin" in base64
  DB_PASSWORD: MTIzNDU2                  # "123456" in base64
  COINGECKO_API_KEY: eHgtY2ctZGVtby1hcGkta2V5 # "xx-cg-demo-api-key" in base64
